function updateHTMLBar(html_handle, pct)
% updateHTMLBar - HTML 프로그레스 바를 업데이트하는 독립 헬퍼 함수
%   html_handle: App Designer의 uihtml 컴포넌트 (app.HTML)
%   pct: 0~100 사이 진행률
    pct = round(min(max(pct, 0), 100));
    barTpl = ['<style>*{margin:0;padding:0;box-sizing:border-box;font-family:Arial,sans-serif;}' ...
      '.title{text-align:center;font-size:10px;color:#999;letter-spacing:2px;margin-bottom:4px;}' ...
      '.row{display:flex;align-items:center;gap:12px;padding:0 4px;}' ...
      '.track{flex:1;background:#d9d9d9;height:30px;border-radius:2px;}' ...
      '.fill{height:100%%;background:#6cc0f5;border-radius:2px;}' ...
      '.val{font-size:32px;font-weight:bold;color:#333;min-width:60px;text-align:right;}' ...
      '.ticks{display:flex;justify-content:space-between;padding:4px 4px 0;font-size:10px;color:#999;}</style>' ...
      '<div class="title">PROGRESS</div>' ...
      '<div class="row"><div class="track"><div class="fill" style="width:%d%%"></div></div>' ...
      '<div class="val">%03d</div></div>' ...
      '<div class="ticks" style="margin-right:72px;">' ...
      '<span>0</span><span>20</span><span>40</span><span>60</span><span>80</span><span>100</span></div>'];
    html_handle.HTMLSource = sprintf(barTpl, pct, pct);
    drawnow;       % limitrate 아닌 full drawnow로 강제 렌더링
    pause(0.05);   % HTML 렌더링 시간 확보 (50ms)
end
